---
version: '3.8'
services:
  lbs:
    container_name: lbs_prod
    build: ./LBS
    ports: [ 5000:5000 ]
    environment:
      # Both the api service and the database
      # - DB_URI=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_LOCAL_DOCKER}:${DATABASE_PORT_LOCAL_DOCKER}/${DATABASE_LBS_NAME}
      # - LOGS_DB=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_LOCAL_DOCKER}:${DATABASE_PORT_LOCAL_DOCKER}/${DATABASE_LOGGER_NAME}
      # or for local docker (API locally, the db remotely)
      - "DB_URI=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_REMOTE}:${DATABASE_PORT_REMOTE}/${DATABASE_LBS_NAME}"
      - "LOGS_DB=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_REMOTE}:${DATABASE_PORT_REMOTE}/${DATABASE_LOGGER_NAME}"
      # Secret key
      - "SECRET_KEY=${SECRET_KEY}"
    depends_on: [ db ]
  db:
    container_name: db_prod
    image: postgres:15.7
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_LBS_NAME}
    volumes: [ .:/docker-entrypoint-initdb.d ]
    ports: [ 5433:5432 ]
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./LBS/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lbs
