version: '3.8'

services:
  lbs:
    build: ./LBS
    ports:
      - "5000:5000"
    environment:
      - "DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"  #prod (docker run)
      #- "DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${REMOTE_IP}:${REMOTE_DB_PORT}/${POSTGRES_DB}" #dev (manual run)
    depends_on:
      - db
  db:
    image: postgres:15.7
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"