---
version: '3.8'
services:
  lbs:
    build: ./LBS
    ports: [5000:5000]
    environment:
      # Option 1. Full docker local environment (application + postgres)
      - "DB_URI=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_LOCAL_DOCKER}:${DATABASE_PORT_LOCAL_DOCKER}/${DATABASE_LBS_NAME}"
      - "LOGS_DB=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_LOCAL_DOCKER}:${DATABASE_PORT_LOCAL_DOCKER}/${DATABASE_LOGGER_NAME}"

      # Option 2. Only application container, the database is hosted somewhere else
      # - "DB_URI=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_REMOTE}:${DATABASE_PORT_REMOTE}/${DATABASE_LBS_NAME}"
      # - "LOGS_DB=postgresql+psycopg2://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST_REMOTE}:${DATABASE_PORT_REMOTE}/${DATABASE_LOGGER_NAME}"
    depends_on: [db]
  db:
    image: postgres:15.7
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_LBS_NAME}
    volumes: [.:/docker-entrypoint-initdb.d]
    ports: [5433:5432]
