version: '3.8'

services:
  lbs:
    build: ./LBS
    ports:
      - "5000:5000"
    environment:
      - DB_URI=postgresql://postgres:aardes123@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:15.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aardes123
      POSTGRES_DB: postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"