name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST_REMOTE: ${{ secrets.DATABASE_HOST_REMOTE }}
          DATABASE_PORT_REMOTE: ${{ secrets.DATABASE_PORT_REMOTE }}
          DATABASE_LBS_NAME: ${{ secrets.DATABASE_LBS_NAME }}
          DATABASE_LOGGER_NAME: ${{ secrets.DATABASE_LOGGER_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Wait for Docker container to be ready
        run: |
          # Wait for the API to be ready
          until $(curl --output /dev/null --silent --head --fail http://localhost:5000); do
            printf '.'
            sleep 5
          done

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: |
          newman run Collections/collection.json -e Collections/environment.json --env-var base_url=http://localhost:5000

      - name: Clean up Docker Compose
        run: |
          docker-compose down
